### PR TITLE
Update release version in x11-calc.metainfo.xml

### PR DESCRIPTION
**Pull request by mike632t**

### CODE REVIEW

**Comment by macmpi** [comment]
Thanks: this will serve as the test-bed release for submission then.
Do you plan to set a related git tag on the actual commit from your repo?
This will ease reference tracking, and I could set relevant info into yaml file for actual build.

**Comment by mike632t** [comment]
Not sure.

I did look into it but the only way I can see to do it from the web UI involves creating a binary release and I've not mastered the production of a Debian package yet!

Might be able to do it from the git CLI but I'll have to experiment on a test repository first..

**Comment by macmpi** [comment]
on WebUI, you don't have to add binary releases: it's optional.

> Might be able to do it from the git CLI but I'll have to experiment on a test repository first..

https://git-scm.com/book/en/v2/Git-Basics-Tagging
(also shows how to delete a tag in case. Note some subtle [twist](https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git/21759466#21759466) if you want to keep original date)

shall I use c25dd22d5ef083a035525453039e277869aee7e2 for 0.11.0122 then?

**Comment by mike632t** [comment]
I'm made a bit of an amateurish stab at it and it seems to have worked

**Pull request merged**
